### PR TITLE
A32NX Documentation

### PR DESCRIPTION
**Pull request by tareksabet**
Added A320 Neo
Checklist
Normal Procedures
Flight crew flow

### CODE REVIEW

**Comment by ErickSharp** [comment]
Category: QA Tester
Name: Erick [Z-6]#6484
Date of testing: Current date 17/01/2021
Version of the sim: N/A
PR Tested: "A320 Neo Documentation #3"
Object of test: Additions to A320 checklist

Testing technique: Looked at changes made to the checklist, scanning for errors or mistakes. 
Steps you've made to test the Pull Request:
1. Scan through the document and check for errors or issues.
2. Page 4: "(Set to 12 O’clock position)" should be  "(Set to 12 o’clock position)"
3. Page 4: "HYD PÄNEL" should be "HYD PANEL" 
4. Page 5: "PA (Volume ON and set at 12’ oclock position)" should be "PA (Volume ON and set at 12 o'clock position)"
5. I also did notice that on page 11, that the Celsius temperature is not converted to Fahrenheit. I am not sure if this is expected.

Flight notes (If required): None
Issues (If Any): Minor character or spelling issues. 
Overall Rating: Good, minor amounts of improvement needed. 
Conclusions of the testing: Overall, the document is very good and is in-depth. All that it needs are corrections to minor issues and perhaps the addition of page numbers for easier organization.

**Review by NathanInnes — COMMENTED** [review]
FBW A32NX NORMAL PROCEDURES amendment recommendations: 

image
Make it clearer that a new section is starting, makes it easier on the eyes.

image
Follow standard branding guidelines or go for a more darker colour.

image
Font size increased below 

Just double check for spelling errors and font size across the documents, spacing and use of colour when branding guidelines can't be met. If you need suggestions on alternative colours I would suggest using this website https://flatuicolors.com/

**Review by NathanInnes — APPROVED** [review]
Looks good now

**Comment by tshomas** [comment]
Category: Non-official Tester
Name: Shomas [Z]
Date of testing: 20/02/2021
Version of the sim: N/A
PR Tested: "A320 Neo Documentation #3"
Object of test: Sanity and Typos check

Page 4: Overhead Panel Checks - BAT 1 & 2 - Currently "Not Lighted" suggest "Not Lit" or "No lights"
Page 4: No Smoking Sign - Currently "ON" suggest "AUTO" - may be differences in airline SOP though
Page 4: PROB/WINDOW HEAT suggest PROBE/WINDOW HEAT

Page 6: LATERAL CONSOL suggest LATERAL CONSOLE

Page 11: POSOTIVE CLIMB suggest POSITIVE CLIMB

Page 13: PEFORMENCE suggest PERFORMANCE

Page 14: AUTO BRAKE - currently says MAX is "not recommended" suggest "not avaliable" as its not selectable at all

Page 16: LAND LISGHT sw suggest LAND LIGHTS
Page 16: APPRAOCH PHASE suggest APPROACH PHASE

Page 17: GRENN DOT suggest GREEN DOT

Page 19: WHEN LADING GEAR suggest WHEN LANDING GEAR
Page 19: CBAIN CALL suggest CABIN CALL

Page 20: PREDECTIVE suggest PREDICTIVE

Page 22: EXTORIOR suggest EXTERIOR

Comments:
-The parking brake is switched off early on in the cockpit checks, never turned back on and then the next point is before pushback where it's turned off again. Suggest maybe leaving it on or adding a line for parking brake on before chocks removal?

-ATC mode AUTO is selected after setting 2000, unsure if this is different airline SOP as I would leave it off until pushback or IFR clearance is given? 

-Wing Anti Ice on taxi-out, page 8. Wing anti-ice is INOP on the ground except for a self test, possibly move that to before takeoff? Could also be a difference in SOP between airlines as there is no harm I can see with leaving it on.

**Comment by Inaxair** [comment]
Any advancement on these documentations?

**Review by NathanInnes — APPROVED** [review]

**Pull request merged**
