### PR TITLE
Addition of A380 documentation

### PR DESCRIPTION
**Pull request by Inaxair**
I'm writing some interesting documentation.

Here are some other docs to do before complete:

- [x] A380 Routes (QA Passed)

- [x] A380X Multicrew Operations (QA Passed)

     - [x] Clarification of roles
     - [x] Standard callouts

- [x] A380X Procedures (QA PASSED)

     - [x] Preliminary cockpit preparation
     - [x] Cockpit preparation
     - [x] Before pushback or start
     - [x] Engine Start
     - [x] After Start
     - [x] Taxi
     - [x] Before Takeoff
     - [x] Takeoff
     - [x] After Takeoff
     - [x] Climb
     - [x] Cruise
     - [x] Descent preparation
     - [x] Descent
     - [x] Precision Approach
     - [x] CAT II and CAT III approach
     - [x] Non-precision approach
     - [x] Visual Approach
     - [x] Landing
     - [x] Go Around
     - [x] After Landing
     - [x] Parking
     - [x] Securing the Aircraft
     - [x] Legality of document

- [x] A380X Checklist (QA Passed)

Please, don't delete my work. Thanks!

### CODE REVIEW

**Review by NathanInnes — COMMENTED** [review]
Do you have a specific source for the A380 routes?

Use of font should be changed to informal and you should remove the credits to yourself on the header and make an amendments history page with credits there. See privacy policy as an example
image

Use of font in the title should be informal.
image

A380X SOP:
I feel like this design should be reconsidered as its uneasy to the eye, since people read left to right the text should start straight away followed by the image of the A380.
image
Should look more like this 
image

image


Should be "Table of Contents". In the Table of Contents I would remove the roman numerals as they are not necessary.

MultiCrew operations:
Make this a table so its easier to interoperate
image
 
Overall:
Check again for use of informal and formal fonts, check for things that may make it easier to read (always keep accessibility in mind) and check for spelling/grammar errors.

**Comment by Inaxair** [comment]
I followed the FlyByWire Branding Guidelines and those were the fonts to be used. I'll change it, but I'm pretty sure these are the fonts stuff:

Cambria 20 for titles
Calibri 10 for text

As of sources, those were diverse, mostly Airbus website, as well as historical data (Plane spotted in this route, etc.)

As of the credit, well that I forgot to remove, I putted there at first so that people who was looking at it to add routes, that they contact me. Let me do that tomorrow

As of the table, well, I was told to remove it due to too much line in the low space by QA, so Idk if it's better or not...

**Comment by Inaxair** [comment]
@NathanInnes Follow up: All things changed for Checklist and Routes

Multicrew, I would decide against making more lines between the two part, but one line to separate between PIC and CAPt stuff

As of the SOP, table of content is changed, cover, well I need to wait someone

**Review by NathanInnes — APPROVED** [review]

**Comment by NathanInnes** [comment]
Good first version. I will merge for now and more can be improved with time.

**Comment by NathanInnes** [comment]
This repository is a little messed up so expect a change in where to find these docs in the future.

**Pull request merged**
